# Generated by Django 5.0.6 on 2024-08-16 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('representantes', '0002_representante_ativo_representante_criado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='representantes.representante'),
        ),
    ]
