# Generated by Django 5.0.6 on 2024-07-12 00:18

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='produtos', variations={'thumbnail': (90, 90)}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso (em gramas)'),
        ),
    ]
