# Generated by Django 5.0.6 on 2024-08-14 13:22

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produtos_imagem_alter_produtos_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='produtos', variations={'thumbnail': (90, 90)}, verbose_name='Imagem'),
        ),
    ]
