# Generated by Django 5.0.6 on 2024-08-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_grupo_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='descricao',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
    ]
