# Generated by Django 5.0.6 on 2024-07-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormasRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('deposito', 'Deposito'), ('cartao_debito', 'Cartão de Débito'), ('cartao_credito', 'Cartão de Crédito'), ('boleto', 'Boleto')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='carrinho',
            name='forma_recebimento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('deposito', 'Deposito'), ('cartao_debito', 'Cartão de Débito'), ('cartao_credito', 'Cartão de Crédito'), ('boleto', 'Boleto')], max_length=20, null=True),
        ),
    ]
