# Generated by Django 5.0.6 on 2024-07-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0002_formasrecebimento_carrinho_forma_recebimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='forma_recebimento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('deposito', 'Deposito'), ('cartao_debito', 'Cartão de Débito'), ('cartao_credito', 'Cartão de Crédito'), ('boleto', 'Boleto')], max_length=20, null=True),
        ),
    ]
