# Generated by Django 5.0.6 on 2024-07-23 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0003_compra_forma_recebimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='forma_recebimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrinho.formasrecebimento'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='forma_recebimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrinho.formasrecebimento'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='peso_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
