# Generated by Django 5.0.6 on 2024-07-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0004_alter_carrinho_forma_recebimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formasrecebimento',
            name='forma',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('deposito', 'Deposito'), ('cartao_debito', 'Cartão de Débito'), ('cartao_credito', 'Cartão de Crédito'), ('boleto', 'Boleto')], max_length=20, unique=True),
        ),
    ]
