# Generated by Django 5.0.6 on 2024-07-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0005_alter_formasrecebimento_forma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='forma_recebimento',
        ),
    ]
