# Generated by Django 5.0.6 on 2024-07-23 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0006_remove_compra_forma_recebimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='criado',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='modificado',
        ),
        migrations.AddField(
            model_name='compra',
            name='forma_recebimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrinho.formasrecebimento'),
        ),
    ]
