# Generated by Django 5.0.6 on 2024-07-23 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0007_remove_compra_ativo_remove_compra_criado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='compra',
            name='criado',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='compra',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Modificação'),
        ),
    ]
