# Generated by Django 5.0.6 on 2024-07-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0008_compra_ativo_compra_criado_compra_modificado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formasrecebimento',
            old_name='forma',
            new_name='forma_recebimento',
        ),
    ]
