# Generated by Django 5.0.6 on 2024-07-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0009_rename_forma_formasrecebimento_forma_recebimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formasrecebimento',
            name='forma_recebimento',
        ),
        migrations.AddField(
            model_name='formasrecebimento',
            name='forma',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('deposito', 'Deposito'), ('cartao_debito', 'Cartão de Débito'), ('cartao_credito', 'Cartão de Crédito'), ('boleto', 'Boleto')], default='dinheiro', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='forma_recebimento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('deposito', 'Deposito'), ('cartao_debito', 'Cartão de Débito'), ('cartao_credito', 'Cartão de Crédito'), ('boleto', 'Boleto')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='forma_recebimento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='peso_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
