# Generated by Django 5.0.6 on 2024-07-24 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0010_remove_formasrecebimento_forma_recebimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formasrecebimento',
            name='forma',
        ),
        migrations.AddField(
            model_name='formasrecebimento',
            name='forma_recebimento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('deposito', 'Deposito'), ('cartao_debito', 'Cartão de Débito'), ('cartao_credito', 'Cartão de Crédito'), ('boleto', 'Boleto')], default='dinheiro', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='forma_recebimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrinho.formasrecebimento'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='forma_recebimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrinho.formasrecebimento'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='peso_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
