# Generated by Django 5.0.6 on 2024-07-24 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0011_remove_formasrecebimento_forma_and_more'),
        ('representantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='representante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='representantes.representante'),
        ),
    ]
