# Generated by Django 5.0.6 on 2024-07-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0013_compra_representante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='forma_recebimento',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='forma_recebimento',
        ),
        migrations.DeleteModel(
            name='FormasRecebimento',
        ),
    ]
