# Generated by Django 5.0.6 on 2024-07-25 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0014_remove_compra_forma_recebimento_and_more'),
        ('formasrecebimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='formasrecebimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formasrecebimento.formasrecebimento'),
        ),
        migrations.AddField(
            model_name='compra',
            name='formasrecebimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formasrecebimento.formasrecebimento'),
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='formasrecebimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formasrecebimento.formasrecebimento'),
        ),
    ]
