# Generated by Django 5.0.6 on 2024-07-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0015_carrinho_formasrecebimento_compra_formasrecebimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='formasrecebimento_descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='representante_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
