# Generated by Django 5.0.6 on 2024-07-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0016_carrinho_formasrecebimento_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='formasrecebimento_descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='representante_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
