# Generated by Django 5.0.6 on 2024-07-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0017_compra_formasrecebimento_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='formasrecebimento_descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
