# Generated by Django 5.0.6 on 2024-07-25 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0018_itemcompra_formasrecebimento_descricao'),
        ('representantes', '0002_representante_ativo_representante_criado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='representante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='representantes.representante'),
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='representante_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
