# Generated by Django 5.0.6 on 2024-07-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='representante',
            name='criado',
            field=models.DateField(auto_now_add=True, default='2024-07-25', verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='representante',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Atualização'),
        ),
    ]
